# -*- mode: python ; coding: utf-8 -*-
import os
import sys

block_cipher = None

project_root = os.path.dirname(os.path.abspath(SPECPATH))

site_packages = 'C:\\Users\\Xu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages'

ok_pyd_files = [
    (os.path.join(site_packages, 'ok', '__init__.cp312-win_amd64.pyd'), 'ok'),
    (os.path.join(site_packages, 'ok', 'device', 'capture.cp312-win_amd64.pyd'), 'ok/device'),
    (os.path.join(site_packages, 'ok', 'feature', 'Box.cp312-win_amd64.pyd'), 'ok/feature'),
    (os.path.join(site_packages, 'ok', 'feature', 'FeatureSet.cp312-win_amd64.pyd'), 'ok/feature'),
    (os.path.join(site_packages, 'ok', 'task', 'task.cp312-win_amd64.pyd'), 'ok/task'),
    (os.path.join(site_packages, 'ok', 'task', 'TaskExecutor.cp312-win_amd64.pyd'), 'ok/task'),
]

a = Analysis(
    ['main.py'],
    pathex=[project_root],
    binaries=ok_pyd_files,
    datas=[
        ('configs', 'configs'),
        ('assets', 'assets'),
        ('i18n', 'i18n'),
        ('icons', 'icons'),
        ('src', 'src'),
        ('config.py', '.'),
    ],
    hiddenimports=[
        'uuid',
        'hashlib',
        'hmac',
        'secrets',
        'PySide6',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.QtNetwork',
        'qfluentwidgets',
        'cv2',
        'numpy',
        'win32gui',
        'win32con',
        'win32api',
        'win32process',
        'win32security',
        'pydirectinput',
        'onnxruntime',
        'onnxruntime.capi',
        'onnxruntime.capi.onnxruntime_binding',
        'adbutils',
        'psutil',
        'pyappify',
        'ok',
        'ok.emulator_base',
        'ok.emulator_windows',
        'ok.platform_windows',
        'ok.utils',
        'ok.capture',
        'ok.capture.adb',
        'ok.capture.adb.deep',
        'ok.capture.adb.minitouch',
        'ok.capture.adb.nemu_ipc',
        'ok.capture.adb.nemu_utils',
        'ok.capture.adb.pool',
        'ok.capture.adb.timer',
        'ok.capture.adb.util',
        'ok.capture.d3d11',
        'ok.capture.dump',
        'ok.device',
        'ok.device.DeviceManager',
        'ok.device.intercation',
        'ok.device.capture',
        'ok.feature',
        'ok.feature.CompressCoco',
        'ok.feature.Feature',
        'ok.feature.Box',
        'ok.feature.FeatureSet',
        'ok.gui',
        'ok.gui.Communicate',
        'ok.gui.MainWindow',
        'ok.gui.MessageWindow',
        'ok.gui.resources',
        'ok.gui.StartController',
        'ok.gui.TabTitles',
        'ok.gui.about',
        'ok.gui.about.AboutTab',
        'ok.gui.about.HttpTextEdit',
        'ok.gui.about.VersionCard',
        'ok.gui.config',
        'ok.gui.config.OKIcon',
        'ok.gui.config.style_sheet',
        'ok.gui.debug',
        'ok.gui.debug.DebugTab',
        'ok.gui.debug.FrameWidget',
        'ok.gui.debug.LogWindow',
        'ok.gui.debug.RunCodeTab',
        'ok.gui.debug.Screenshot',
        'ok.gui.i18n',
        'ok.gui.i18n.GettextTranslator',
        'ok.gui.i18n.path',
        'ok.gui.i18n.update',
        'ok.gui.launcher',
        'ok.gui.launcher.DownloadBar',
        'ok.gui.launcher.LauncherWindow',
        'ok.gui.launcher.LinksBar',
        'ok.gui.launcher.RunBar',
        'ok.gui.launcher.UpdateBar',
        'ok.gui.overlay',
        'ok.gui.overlay.OverlayWindow',
        'ok.gui.setting',
        'ok.gui.setting.GlobalConfigCard',
        'ok.gui.setting.SettingTab',
        'ok.gui.start',
        'ok.gui.start.SelectCaptureListView',
        'ok.gui.start.StartCard',
        'ok.gui.start.StartTab',
        'ok.gui.tasks',
        'ok.gui.tasks.ConfigCard',
        'ok.gui.tasks.ConfigItemFactory',
        'ok.gui.tasks.ConfigLabelAndWidget',
        'ok.gui.tasks.LabelAndDoubleSpinBox',
        'ok.gui.tasks.LabelAndDropDown',
        'ok.gui.tasks.LabelAndGlobal',
        'ok.gui.tasks.LabelAndLineEdit',
        'ok.gui.tasks.LabelAndList',
        'ok.gui.tasks.LabelAndMultiSelection',
        'ok.gui.tasks.LabelAndSpinBox',
        'ok.gui.tasks.LabelAndSwitchButton',
        'ok.gui.tasks.LabelAndTextEdit',
        'ok.gui.tasks.LabelAndWidget',
        'ok.gui.tasks.ModifyListDialog',
        'ok.gui.tasks.ModifyListItem',
        'ok.gui.tasks.OneTimeTaskTab',
        'ok.gui.tasks.StartButton',
        'ok.gui.tasks.TaskCard',
        'ok.gui.tasks.TaskManger',
        'ok.gui.tasks.TaskOpButton',
        'ok.gui.tasks.TaskTab',
        'ok.gui.tasks.TooltipTableWidget',
        'ok.gui.tasks.TriggerTaskTab',
        'ok.gui.util',
        'ok.gui.util.Alert',
        'ok.gui.util.app',
        'ok.gui.util.download',
        'ok.gui.util.InitWorker',
        'ok.gui.util.pip_util',
        'ok.gui.widget',
        'ok.gui.widget.BaseLoading',
        'ok.gui.widget.BaseWindow',
        'ok.gui.widget.Card',
        'ok.gui.widget.CustomTab',
        'ok.gui.widget.EmptyCard',
        'ok.gui.widget.FlowLayout',
        'ok.gui.widget.FramelessDialog',
        'ok.gui.widget.ImageWidget',
        'ok.gui.widget.ListTableWidgetItem',
        'ok.gui.widget.NumericTableWidgetItem',
        'ok.gui.widget.OkCompactSpinBox',
        'ok.gui.widget.RedPrimaryButton',
        'ok.gui.widget.SortingTableWidgetItem',
        'ok.gui.widget.StartLoadingDialog',
        'ok.gui.widget.StatusBar',
        'ok.gui.widget.Tab',
        'ok.gui.widget.TabWidget',
        'ok.gui.widget.UpdateConfigWidgetItem',
        'ok.gui.widget.WidgetWithVLabel',
        'ok.gui.widget.YesNonWidgetItem',
        'ok.ocr',
        'ok.ocr.download_paddle_model',
        'ok.rotypes',
        'ok.rotypes.delegate',
        'ok.rotypes.export',
        'ok.rotypes.idldsl',
        'ok.rotypes.inspectable',
        'ok.rotypes.roapi',
        'ok.rotypes.types',
        'ok.rotypes.winstring',
        'ok.task',
        'ok.task.Collections',
        'ok.task.DiagnosisTask',
        'ok.task.exceptions',
        'ok.task.task',
        'ok.task.TaskExecutor',
        'ok.test',
        'ok.test.OKTestRunner',
        'ok.test.RunTests',
        'ok.test.TaskTestCase',
        'ok.update',
        'ok.update.paperclip',
        'ok.update.copy_ok_folder',
        'ok.update.gen_md5',
        'ok.update.GitUpdater',
        'ok.update.init_launcher_env',
        'ok.update.inline_ok_requirements',
        'ok.util',
        'ok.util.Analytics',
        'ok.util.clazz',
        'ok.util.collection',
        'ok.util.color',
        'ok.util.config',
        'ok.util.file',
        'ok.util.GlobalConfig',
        'ok.util.handler',
        'ok.util.i18n',
        'ok.util.logger',
        'ok.util.partial_sync_repo',
        'ok.util.process',
        'ok.util.window',
        'src',
        'src.task',
        'src.scene',
        'src.utils',
        'src.utils.ResolutionAdapter',
        'src.utils.BackgroundManager',
        # onnxocr 模块
        'onnxocr',
        'onnxocr.onnx_paddleocr',
        'onnxocr.predict_system',
        'onnxocr.predict_det',
        'onnxocr.predict_rec',
        'onnxocr.predict_cls',
        'onnxocr.utils',
        'onnxocr.operators',
        'onnxocr.imaug',
        'onnxocr.db_postprocess',
        'onnxocr.cls_postprocess',
        'onnxocr.rec_postprocess',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'scipy',
        'pandas',
        'IPython',
        'jupyter',
        'notebook',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ok-jump',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
